'use client'
import Link from 'next/link'
import { useAdmin } from '@/lib/admin-context'
import { AlertTriangle, Bell, Clock3, FileWarning, Store } from 'lucide-react'
export default function AdminNotificationsPage() {
  const { providers, orders } = useAdmin(); const now=Date.now(); const thirtyDays=30*86400000
  const pendingProviders=providers.filter(p=>p.status==='pending')
  const stalledPayments=orders.filter(o=>o.payment_method==='qrph'&&o.payment_status==='pending'&&now-new Date(o.created_at).getTime()>30*60000)
  const expiring=providers.flatMap(p=>[{provider:p,label:'Business permit',date:p.business_permit_expires_at},{provider:p,label:'Owner ID',date:p.owner_id_expires_at}]).filter(item=>item.date&&new Date(item.date).getTime()-now<thirtyDays)
  const highCancellation=providers.map(provider=>{const own=orders.filter(o=>o.provider_id===provider.id);const cancelled=own.filter(o=>o.status==='cancelled').length;return{provider,total:own.length,rate:own.length?cancelled/own.length:0}}).filter(item=>item.total>=5&&item.rate>=.3)
  const count=pendingProviders.length+stalledPayments.length+expiring.length+highCancellation.length
  return <div><div className="mb-7"><h1 className="text-3xl font-black">Admin notifications</h1><p className="mt-2 text-sm text-gray-500">Operational issues that need review, generated from live platform data.</p></div>{count===0?<div className="rounded-2xl border border-dashed border-gray-300 bg-white py-20 text-center"><Bell className="mx-auto h-11 w-11 text-gray-300"/><p className="mt-4 font-black">Everything looks clear</p></div>:<div className="space-y-3">{pendingProviders.map(p=><Notice key={`p-${p.id}`} icon={<Store/>} title={`${p.store_name} is waiting for approval`} detail="Review documents and activate or reject this provider." href="/admin/providers"/>)}{stalledPayments.map(o=><Notice key={`o-${o.id}`} icon={<Clock3/>} title={`QR Ph payment may be stalled · #${o.id.slice(-6).toUpperCase()}`} detail={`${o.customer_name} · ₱${o.total_amount.toLocaleString()}`} href="/admin/orders"/>)}{expiring.map((item,index)=><Notice key={`e-${item.provider.id}-${index}`} icon={<FileWarning/>} title={`${item.label} ${new Date(item.date!).getTime()<now?'expired':'expires soon'}`} detail={`${item.provider.store_name} · ${new Date(item.date!).toLocaleDateString('en-PH')}`} href="/admin/providers"/>)}{highCancellation.map(item=><Notice key={`c-${item.provider.id}`} icon={<AlertTriangle/>} title={`${item.provider.store_name} has a high cancellation rate`} detail={`${Math.round(item.rate*100)}% across ${item.total} orders`} href="/admin/orders"/>)}</div>}</div>
}
function Notice({icon,title,detail,href}:{icon:React.ReactNode;title:string;detail:string;href:string}){return <Link href={href} className="flex min-h-24 items-center gap-4 rounded-2xl border border-gray-200 bg-white p-5 hover:border-indigo-200 hover:shadow-sm"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-50 text-amber-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><span className="min-w-0 flex-1"><span className="block font-black text-gray-900">{title}</span><span className="mt-1 block text-sm text-gray-500">{detail}</span></span></Link>}
