'use client'

import { useEffect, useMemo, useState } from 'react'
import { useProvider } from '@/lib/provider-context'
import { supabase } from '@/lib/supabase'
import { BarChart3, Banknote, CalendarDays, Download, Plus, Receipt, ShoppingBag, Trash2, TrendingDown, TrendingUp, X } from 'lucide-react'

type ManualSale={id:string;product_id:string|null;product_name:string|null;category:'water'|'lpg'|'other';quantity:number;total_amount:number;payment_method:string;customer_name:string|null;notes:string|null;sold_at:string}
const money=(n:number)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2}).format(n)
const csv=(name:string,rows:Record<string,unknown>[])=>{if(!rows.length)return;const heads=Object.keys(rows[0]);const clean=(v:unknown)=>`"${String(v??'').replace(/"/g,'""')}"`;const blob=new Blob([[heads.join(','),...rows.map(row=>heads.map(h=>clean(row[h])).join(','))].join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}

export default function ProviderAnalyticsPage(){
 const{store,orders,products}=useProvider();const today=new Date().toISOString().slice(0,10);const[start,setStart]=useState(today);const[end,setEnd]=useState(today);const[manual,setManual]=useState<ManualSale[]>([]);const[showAdd,setShowAdd]=useState(false);const[error,setError]=useState('');const[saving,setSaving]=useState(false)
 const[form,setForm]=useState({product_id:'',category:'water',quantity:'1',amount:'',payment:'cash',customer:'',notes:'',sold_at:new Date().toISOString().slice(0,16),reduce_stock:false})
 async function load(){if(!store)return;const{data,error}=await supabase.from('provider_manual_sales').select('*').eq('provider_id',store.id).order('sold_at',{ascending:false});if(error)setError(error.message);else setManual((data||[]).map((s:any)=>({...s,total_amount:Number(s.total_amount)})))}
 useEffect(()=>{load()},[store?.id])
 const from=new Date(`${start}T00:00:00`).getTime(),to=new Date(`${end}T23:59:59`).getTime();const days=Math.max(1,Math.round((to-from)/86400000)+1);const previousFrom=from-days*86400000,previousTo=from-1
 const online=orders.filter(o=>o.status==='delivered').map(o=>({id:o.id,date:o.updated_at,amount:Number(o.total_amount),payment:o.payment_method,source:'AquaGas order',description:o.items.map(i=>`${i.product_name} ×${i.quantity}`).join(' · ')}))
 const outside=manual.map(s=>({id:s.id,date:s.sold_at,amount:s.total_amount,payment:s.payment_method,source:'Recorded outside AquaGas',description:s.product_name?`${s.product_name} ×${s.quantity}`:`${s.category} sale`}))
 const all=[...online,...outside];const selected=all.filter(s=>{const t=new Date(s.date).getTime();return t>=from&&t<=to});const previous=all.filter(s=>{const t=new Date(s.date).getTime();return t>=previousFrom&&t<=previousTo})
 const revenue=selected.reduce((a,s)=>a+s.amount,0),previousRevenue=previous.reduce((a,s)=>a+s.amount,0),change=previousRevenue?((revenue-previousRevenue)/previousRevenue)*100:revenue?100:0;const average=selected.length?revenue/selected.length:0;const manualRevenue=selected.filter(s=>s.source.startsWith('Recorded')).reduce((a,s)=>a+s.amount,0)
 const daily=useMemo(()=>Array.from({length:Math.min(days,366)},(_,i)=>{const d=new Date(from+i*86400000);const key=d.toISOString().slice(0,10);return{key,label:d.toLocaleDateString('en-PH',{month:'short',day:'numeric'}),amount:selected.filter(s=>s.date.slice(0,10)===key).reduce((a,s)=>a+s.amount,0)}}),[from,to,selected.length,revenue]);const max=Math.max(...daily.map(d=>d.amount),1)
 function preset(n:number){const e=new Date();const s=new Date(Date.now()-(n-1)*86400000);setEnd(e.toISOString().slice(0,10));setStart(s.toISOString().slice(0,10))}
 async function record(){if(!form.amount||Number(form.quantity)<1)return;setSaving(true);setError('');const{error}=await supabase.rpc('record_provider_manual_sale',{p_product_id:form.product_id||null,p_category:form.category,p_quantity:Number(form.quantity),p_total_amount:Number(form.amount),p_payment_method:form.payment,p_customer_name:form.customer,p_notes:form.notes,p_sold_at:new Date(form.sold_at).toISOString(),p_reduce_stock:form.reduce_stock});if(error)setError(error.message);else{setShowAdd(false);setForm(f=>({...f,product_id:'',quantity:'1',amount:'',customer:'',notes:'',reduce_stock:false}));await load()}setSaving(false)}
 async function remove(id:string){if(!confirm('Remove this manual sale from analytics? Stock changes are not reversed.'))return;const{error}=await supabase.from('provider_manual_sales').delete().eq('id',id);if(error)setError(error.message);else load()}
 function exportSales(){csv(`aquagas-sales-${start}-to-${end}.csv`,selected.sort((a,b)=>b.date.localeCompare(a.date)).map(s=>({Date:new Date(s.date).toLocaleString('en-PH'),Source:s.source,Description:s.description,Payment:s.payment,Amount:s.amount})))}
 return <div className="space-y-7"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight text-gray-950 dark:text-white">Shop analytics</h1><p className="mt-2 text-sm text-gray-500">Combine delivered AquaGas orders with sales recorded at your shop.</p></div><div className="flex flex-wrap gap-2"><button onClick={exportSales} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 text-sm font-bold"><Download className="h-4 w-4"/>Export CSV</button><button onClick={()=>setShowAdd(true)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-water-600 px-4 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Record shop sale</button></div></header>
 {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 <section className="flex flex-col gap-3 rounded-2xl border border-gray-200 bg-white p-4 lg:flex-row lg:items-center"><div className="flex flex-wrap gap-2">{[[1,'Today'],[7,'7 days'],[30,'30 days'],[90,'3 months']].map(([n,label])=><button key={String(n)} onClick={()=>preset(Number(n))} className="min-h-10 rounded-xl bg-gray-100 px-3 text-sm font-bold text-gray-700 hover:bg-water-50 hover:text-water-700">{label}</button>)}</div><div className="flex flex-1 flex-wrap items-center gap-2 lg:justify-end"><CalendarDays className="h-4 w-4 text-gray-400"/><input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)} className="h-10 rounded-xl border border-gray-200 px-3 text-sm"/><span className="text-sm text-gray-400">to</span><input type="date" value={end} min={start} max={today} onChange={e=>setEnd(e.target.value)} className="h-10 rounded-xl border border-gray-200 px-3 text-sm"/></div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Banknote/>} label="Total shop sales" value={money(revenue)} detail={`${selected.length} transactions`}/><Metric icon={change>=0?<TrendingUp/>:<TrendingDown/>} label="Period comparison" value={`${change>=0?'+':''}${change.toFixed(1)}%`} detail={`Previous ${days} days`}/><Metric icon={<ShoppingBag/>} label="Average sale" value={money(average)} detail="Across all sales"/><Metric icon={<Receipt/>} label="Outside-system sales" value={money(manualRevenue)} detail="Not included in payouts"/></section>
 <section className="rounded-2xl border border-gray-200 bg-white p-5"><div className="mb-6 flex items-center justify-between"><div><h2 className="font-black text-gray-950">Sales by day</h2><p className="mt-1 text-xs text-gray-500">Delivered orders and manual shop entries</p></div><BarChart3 className="h-5 w-5 text-water-500"/></div><div className="flex h-52 min-w-[520px] items-end gap-2 overflow-x-auto pb-6">{daily.map(day=><div key={day.key} className="flex min-w-10 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] font-bold text-gray-500">{day.amount?`₱${Math.round(day.amount)}`:''}</span><div className="w-full rounded-t-lg bg-water-500" style={{height:`${Math.max(day.amount/max*140,day.amount?5:1)}px`}}/><span className="whitespace-nowrap text-[10px] text-gray-400">{day.label}</span></div>)}</div></section>
 <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-xl font-black">Transactions</h2><p className="mt-1 text-sm text-gray-500">Every sale in the selected period</p></div></div><div className="overflow-hidden rounded-2xl border border-gray-200 bg-white">{selected.length===0?<p className="py-14 text-center text-sm text-gray-500">No sales in this date range.</p>:selected.sort((a,b)=>b.date.localeCompare(a.date)).map(s=><div key={`${s.source}-${s.id}`} className="flex items-center gap-4 border-b border-gray-100 p-4 last:border-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-100"><Receipt className="h-4 w-4 text-gray-600"/></span><div className="min-w-0 flex-1"><p className="truncate font-bold text-gray-900">{s.description}</p><p className="mt-1 text-xs text-gray-500">{s.source} · {new Date(s.date).toLocaleString('en-PH')} · {s.payment}</p></div><p className="font-black">{money(s.amount)}</p>{s.source.startsWith('Recorded')&&<button onClick={()=>remove(s.id)} aria-label="Delete manual sale" className="flex h-10 w-10 items-center justify-center rounded-xl text-gray-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4"/></button>}</div>)}</div></section>
 {showAdd&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 p-4 sm:items-center"><div className="max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">Record a shop sale</h2><p className="mt-1 text-sm text-gray-500">This entry affects analytics only, never your AquaGas wallet.</p></div><button onClick={()=>setShowAdd(false)} className="flex h-10 w-10 items-center justify-center rounded-xl hover:bg-gray-100"><X className="h-5 w-5"/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Date and time"><input type="datetime-local" value={form.sold_at} onChange={e=>setForm({...form,sold_at:e.target.value})}/></Field><Field label="Payment"><select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})}><option value="cash">Cash</option><option value="gcash">GCash</option><option value="qrph">QR Ph</option><option value="other">Other</option></select></Field><Field label="Product (optional)"><select value={form.product_id} onChange={e=>{const p=products.find(x=>x.id===e.target.value);setForm({...form,product_id:e.target.value,category:p?.category||form.category})}}><option value="">General sale</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · stock {p.stock_quantity}</option>)}</select></Field><Field label="Category"><select disabled={!!form.product_id} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="water">Water</option><option value="lpg">LPG</option><option value="other">Other</option></select></Field><Field label="Quantity"><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></Field><Field label="Total amount (₱)"><input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Customer name (optional)"><input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></Field><Field label="Notes (optional)"><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div>{form.product_id&&<label className="mt-4 flex min-h-12 items-center gap-3 rounded-xl bg-amber-50 px-4 text-sm font-semibold text-amber-900"><input type="checkbox" checked={form.reduce_stock} onChange={e=>setForm({...form,reduce_stock:e.target.checked})}/>Reduce AquaGas product stock by {form.quantity||0}</label>}<button onClick={record} disabled={saving||!form.amount||Number(form.quantity)<1} className="mt-6 min-h-12 w-full rounded-xl bg-water-600 font-black text-white disabled:opacity-40">{saving?'Saving sale…':'Save manual sale'}</button></div></div>}
 </div>
}
function Metric({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="rounded-2xl border border-gray-200 bg-white p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-water-50 text-water-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><p className="mt-5 text-2xl font-black text-gray-950">{value}</p><p className="mt-1 text-sm font-bold text-gray-700">{label}</p><p className="mt-1 text-xs text-gray-400">{detail}</p></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-bold text-gray-600">{label}<span className="mt-1 block [&_input]:h-11 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-gray-200 [&_input]:px-3 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:border-gray-200 [&_select]:bg-white [&_select]:px-3">{children}</span></label>}
