'use client'
import { useEffect, useMemo, useState } from 'react'
import { useAdmin } from '@/lib/admin-context'
import { supabase } from '@/lib/supabase'
import { Receipt as ReceiptText } from 'lucide-react'
type Refund = { id: string; order_id: string; amount: number; reason: string; status: string; reference_number: string | null; requested_at: string }
export default function RefundsPage() {
  const { orders } = useAdmin(); const [refunds, setRefunds] = useState<Refund[]>([]); const [orderId, setOrderId] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState('')
  const eligible = useMemo(() => orders.filter(order => order.payment_method === 'qrph' && order.payment_status === 'paid' && !refunds.some(refund => refund.order_id === order.id && !['rejected','failed'].includes(refund.status))), [orders, refunds])
  async function load() { const { data, error } = await supabase.from('payment_refunds').select('*').order('requested_at', { ascending: false }); setRefunds((data || []).map((r:any)=>({...r,amount:Number(r.amount)}))); setError(error?.message || '') }
  useEffect(() => { load() }, [])
  async function create() { const order = orders.find(item => item.id === orderId); if (!order || !reason.trim()) return; const { error } = await supabase.from('payment_refunds').insert({ order_id: order.id, amount: order.total_amount, reason: reason.trim(), status: 'requested' }); if(error)setError(error.message); else {setOrderId('');setReason('');load()} }
  async function update(refund: Refund, status: string) { const ref = status === 'completed' ? prompt('Enter the PayMongo/GCash refund reference number:') : null; if(status==='completed'&&!ref)return; const {error}=await supabase.from('payment_refunds').update({status,reference_number:ref,processed_at:['completed','rejected'].includes(status)?new Date().toISOString():null}).eq('id',refund.id); if(error)setError(error.message);else load() }
  return <div className="space-y-6"><div><h1 className="text-3xl font-black">QR Ph refunds</h1><p className="mt-2 text-sm text-gray-500">Track refund reviews and external payment references. “Completed” must only be used after money is returned.</p></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<section className="rounded-2xl border border-gray-200 bg-white p-5"><h2 className="font-black">Create refund case</h2><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_1fr_auto]"><select value={orderId} onChange={e=>setOrderId(e.target.value)} className="h-12 rounded-xl border border-gray-200 px-3"><option value="">Select paid QR Ph order</option>{eligible.map(order=><option key={order.id} value={order.id}>#{order.id.slice(-6).toUpperCase()} · {order.customer_name} · ₱{order.total_amount}</option>)}</select><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Refund reason" className="h-12 rounded-xl border border-gray-200 px-4"/><button onClick={create} disabled={!orderId||!reason.trim()} className="min-h-12 rounded-xl bg-indigo-600 px-5 font-bold text-white disabled:opacity-40">Create case</button></div></section><div className="space-y-3">{refunds.length===0?<div className="rounded-2xl border border-dashed border-gray-300 bg-white py-16 text-center"><ReceiptText className="mx-auto h-10 w-10 text-gray-300"/><p className="mt-3 font-bold">No refund cases</p></div>:refunds.map(refund=><article key={refund.id} className="flex flex-col gap-4 rounded-2xl border border-gray-200 bg-white p-5 lg:flex-row lg:items-center"><div className="flex-1"><p className="font-black">Order #{refund.order_id.slice(-6).toUpperCase()} · ₱{refund.amount.toLocaleString()}</p><p className="mt-1 text-sm text-gray-500">{refund.reason}</p><p className="mt-2 text-xs text-gray-400">{new Date(refund.requested_at).toLocaleString('en-PH')} {refund.reference_number&&`· Ref ${refund.reference_number}`}</p></div><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold capitalize">{refund.status}</span>{!['completed','rejected'].includes(refund.status)&&<div className="flex gap-2"><button onClick={()=>update(refund,'processing')} className="rounded-xl bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700">Processing</button><button onClick={()=>update(refund,'completed')} className="rounded-xl bg-green-600 px-3 py-2 text-sm font-bold text-white">Complete</button><button onClick={()=>update(refund,'rejected')} className="rounded-xl bg-red-50 px-3 py-2 text-sm font-bold text-red-700">Reject</button></div>}</article>)}</div></div>
}
